### ISSUE TITLE
Cannot clone the 'cmake_strict_defaults' sub-module

### ISSUE THREAD

**Issue by poyenc** [davidstone/operators#1]
Hello, 

I'd like to play with the [**bounded_integer**](https://bitbucket.org/davidstone/bounded_integer/src/master/) library but I can not clone all the _maybe_ necessary sub-modules like **cmake_strict_defaults**.

The root cause is that the **cmake_strict_defaults** repository was added as sub-module by **Git** protocol, rather than **HTTPS** protocol, thus others cannot even clone sub-module without permissions.

```bash
$ cat .gitmodules
[submodule "cmake_strict_defaults"]
        path = cmake_strict_defaults
        url = git@github.com:davidstone/cmake_strict_defaults.git
```

**Comment by davidstone** [comment]
Thank you, I have fixed this
